name: React Deploy

on:
  push: 
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - name: Set up Node.js ${{ matrix.node-version }} 
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/checkout@v1
      
      - name: npm install
        run: |
          npm install
      
      - name: npm build
        run: |
          npm run build

     